// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx68UIixG08Y_v4MeACUQ3ixBiHXHjY8I',
    appId: '1:21476635686:web:b2f8cb94b59e00d0f562e7',
    messagingSenderId: '21476635686',
    projectId: 'fir-e8b4f',
    authDomain: 'fir-e8b4f.firebaseapp.com',
    storageBucket: 'fir-e8b4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5t9XN86r5DJwlEQ2_ATtyAJblpXhq1_A',
    appId: '1:21476635686:android:80dd998b6c812d68f562e7',
    messagingSenderId: '21476635686',
    projectId: 'fir-e8b4f',
    storageBucket: 'fir-e8b4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Z_HfIImqdxWy5KZJnq6LZ7lcj9TCYLc',
    appId: '1:21476635686:ios:1a950d1ab5ef7438f562e7',
    messagingSenderId: '21476635686',
    projectId: 'fir-e8b4f',
    storageBucket: 'fir-e8b4f.appspot.com',
    iosBundleId: 'com.example.carService',
  );
}
